/**
 * security.c — Cryptographic verification for OTA firmware updates.
 *
 * Implements:
 *  1. verify_sha256()           — mbedTLS SHA-256 digest comparison
 *  2. verify_ecc_signature()    — mbedTLS ECDSA-P256 pk_verify
 *  3. is_nonce_fresh()          — replay-attack prevention (timestamp + seen-nonce cache)
 *
 * The ECC public key is embedded at compile time. Replace the placeholder PEM
 * with the actual P-256 public key generated by your signing tool:
 *
 *   openssl ecparam -name prime256v1 -genkey -noout -out ota-key.pem
 *   openssl ec -in ota-key.pem -pubout -out ota-pubkey.pem
 */

#include "security.h"

#include <string.h>
#include <time.h>

#include "esp_log.h"
#include "mbedtls/base64.h"
#include "mbedtls/md.h"
#include "mbedtls/pk.h"

static const char *TAG = "security";

/* ── Embedded P-256 public key ──────────────────────────────────────────── */
/* Replace the placeholder key below with your actual generated public key.  */
static const char *OTA_PUBKEY_PEM =
    "-----BEGIN PUBLIC KEY-----\n"
    "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AA==\n"
    "-----END PUBLIC KEY-----\n";

/* ── Nonce cache (recent 32 nonces to detect replays) ───────────────────── */
#define NONCE_CACHE_SIZE 32
static char s_seen_nonces[NONCE_CACHE_SIZE][48];
static int  s_nonce_head = 0;

static bool nonce_is_duplicate(const char *nonce) {
    for (int i = 0; i < NONCE_CACHE_SIZE; i++) {
        if (strncmp(s_seen_nonces[i], nonce, 47) == 0) {
            return true;
        }
    }
    return false;
}

static void nonce_record(const char *nonce) {
    strncpy(s_seen_nonces[s_nonce_head], nonce, 47);
    s_seen_nonces[s_nonce_head][47] = '\0';
    s_nonce_head = (s_nonce_head + 1) % NONCE_CACHE_SIZE;
}

/* ── verify_sha256 ──────────────────────────────────────────────────────── */
bool verify_sha256(const uint8_t *image, size_t len, const char *expected_hex) {
    if (!image || !expected_hex || strlen(expected_hex) != 64) {
        return false;
    }

    uint8_t digest[32];
    mbedtls_md_context_t ctx;
    mbedtls_md_init(&ctx);

    const mbedtls_md_info_t *info = mbedtls_md_info_from_type(MBEDTLS_MD_SHA256);
    if (mbedtls_md_setup(&ctx, info, 0) != 0 ||
        mbedtls_md_starts(&ctx)            != 0 ||
        mbedtls_md_update(&ctx, image, len)!= 0 ||
        mbedtls_md_finish(&ctx, digest)    != 0) {
        mbedtls_md_free(&ctx);
        ESP_LOGE(TAG, "SHA-256 computation failed");
        return false;
    }
    mbedtls_md_free(&ctx);

    /* Convert digest to lowercase hex and compare */
    char computed_hex[65];
    for (int i = 0; i < 32; i++) {
        snprintf(computed_hex + (i * 2), 3, "%02x", digest[i]);
    }

    bool ok = (strncmp(computed_hex, expected_hex, 64) == 0);
    if (!ok) {
        ESP_LOGE(TAG, "SHA-256 MISMATCH: got %.16s... expected %.16s...", computed_hex, expected_hex);
    }
    return ok;
}

/* ── verify_ecc_signature ───────────────────────────────────────────────── */
bool verify_ecc_signature(const uint8_t hash32[32], const char *signature_b64) {
    if (!hash32 || !signature_b64) return false;

    /* Base64-decode the DER-encoded ECDSA signature */
    uint8_t sig_der[128];
    size_t  sig_der_len = 0;
    if (mbedtls_base64_decode(sig_der, sizeof(sig_der), &sig_der_len,
                              (const uint8_t *)signature_b64,
                              strlen(signature_b64)) != 0) {
        ESP_LOGE(TAG, "signature base64 decode failed");
        return false;
    }

    /* Parse the embedded public key */
    mbedtls_pk_context pk;
    mbedtls_pk_init(&pk);
    int rc = mbedtls_pk_parse_public_key(
        &pk,
        (const uint8_t *)OTA_PUBKEY_PEM,
        strlen(OTA_PUBKEY_PEM) + 1   /* include null terminator */
    );
    if (rc != 0) {
        mbedtls_pk_free(&pk);
        ESP_LOGE(TAG, "public key parse failed: -0x%X", (unsigned)(-rc));
        return false;
    }

    /* Verify the ECDSA signature */
    rc = mbedtls_pk_verify(&pk, MBEDTLS_MD_SHA256, hash32, 32, sig_der, sig_der_len);
    mbedtls_pk_free(&pk);

    if (rc != 0) {
        ESP_LOGE(TAG, "ECC signature INVALID: -0x%X", (unsigned)(-rc));
        return false;
    }
    ESP_LOGI(TAG, "ECC signature valid");
    return true;
}

/* ── is_nonce_fresh ─────────────────────────────────────────────────────── */
/*
 * Minimal RFC3339 parser: "2026-04-18T08:39:00Z"
 * Returns seconds since epoch, or 0 on parse error.
 */
static time_t parse_rfc3339(const char *s) {
    if (!s || strlen(s) < 20) return 0;
    struct tm t = {0};
    /* sscanf format matches: YYYY-MM-DDTHH:MM:SSZ */
    if (sscanf(s, "%4d-%2d-%2dT%2d:%2d:%2dZ",
               &t.tm_year, &t.tm_mon, &t.tm_mday,
               &t.tm_hour, &t.tm_min, &t.tm_sec) != 6) {
        return 0;
    }
    t.tm_year -= 1900;
    t.tm_mon  -= 1;
    return mktime(&t); /* NOTE: mktime uses local TZ; for UTC offset handling set TZ="UTC" */
}

bool is_nonce_fresh(const char *nonce, const char *issued_at_iso, int ttl_seconds) {
    if (!nonce || !issued_at_iso) return false;

    /* Replay check */
    if (nonce_is_duplicate(nonce)) {
        ESP_LOGW(TAG, "replay detected: nonce '%s' already seen", nonce);
        return false;
    }

    /* TTL check */
    time_t issued = parse_rfc3339(issued_at_iso);
    time_t now    = time(NULL);
    if (issued == 0) {
        ESP_LOGW(TAG, "cannot parse issued_at: %s — skipping TTL check", issued_at_iso);
    } else {
        double age = difftime(now, issued);
        if (age < 0 || age > (double)ttl_seconds) {
            ESP_LOGW(TAG, "OTA command expired: age=%.0fs TTL=%ds", age, ttl_seconds);
            return false;
        }
    }

    nonce_record(nonce);
    return true;
}
